### ISSUE TITLE
Create rules for projects in the list

### ISSUE THREAD

**Issue by Sean-Der** [pion/awesome-pion#2]
@xsbchen what do you think of creating rules for projects in the list?

I think it would be nice to say `Projects must be on the latest major version of Pion WebRTC`, if they are not maybe we can mark them? It could be a good opportunity for others to help update the projects!

**Comment by xsbchen** [comment]
Agree! I think the main purpose of this list is help developers use Pion more easily, right?

**Comment by Sean-Der** [comment]
I think things are good as is! I don't want to create rules that scare off contributors. When we have dead links people have been reporting them.
